# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cGXwRk_PlfOlPooBKIFXgcO21QKtw4ja
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import io

# Load the uploaded file into a DataFrame
df = pd.read_csv(io.BytesIO(uploaded['museum_visitors.csv']))
print(df.head())

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
print("Setup Complete")

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
print("Setup Complete")

# Display the first few rows of the DataFrame to confirm it's loaded
df.head()

# Print the last five rows of the DataFrame
df.tail()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Example DataFrame setup with data from 2014 to 2018
data = {
    'Museum': [
        'Chinese American Museum', 'Chinese American Museum', 'Chinese American Museum',
        'Chinese American Museum', 'Chinese American Museum', 'Chinese American Museum',
        'Chinese American Museum', 'Chinese American Museum', 'Chinese American Museum',
        'Chinese American Museum', 'Chinese American Museum', 'Chinese American Museum'
    ],
    'Date': [
        '2014-07-01', '2014-08-01', '2015-07-01', '2015-08-01',
        '2016-07-01', '2016-08-01', '2017-07-01', '2017-08-01',
        '2018-07-01', '2018-08-01', '2018-09-01', '2018-10-01'
    ],
    'Visitors': [100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650]
}

# Create DataFrame
df_museum_visitors_data = pd.DataFrame(data)

# Convert 'Date' to datetime format
df_museum_visitors_data['Date'] = pd.to_datetime(df_museum_visitors_data['Date'])

# Plotting
plt.figure(figsize=(12, 6))

# Line plot for the Chinese American Museum
sns.lineplot(data=df_museum_visitors_data, x='Date', y='Visitors', hue='Museum')

# Adding titles and labels
plt.title('Chinese American Museum Visitors Over Time (2014-2018)')
plt.xlabel('Date')
plt.ylabel('Number of Visitors')

# Adjust x-axis to cover the full range from 2014 to 2018
plt.xlim(pd.Timestamp('2014-01-01'), pd.Timestamp('2018-12-31'))

# Show the plot
plt.show()

import pandas as pd

# Example DataFrame
data = {
    'Museum': ['Chinese American Museum', 'Chinese American Museum', 'Avila Adobe', 'Firehouse Museum'],
    'Date': ['2018-07-01', '2018-07-15', '2018-10-01', '2018-10-15'],
    'Visitors': [100, 2620, 19280, 4622]
}
df_museum_visitors_data = pd.DataFrame(data)

# Convert 'Date' to datetime format
df_museum_visitors_data['Date'] = pd.to_datetime(df_museum_visitors_data['Date'])

# Calculate the number of visitors for the Chinese American Museum in July 2018
ca_museum_jul18 = df_museum_visitors_data[
    (df_museum_visitors_data['Museum'] == 'Chinese American Museum') &
    (df_museum_visitors_data['Date'].dt.to_period('M') == '2018-07')
]['Visitors'].sum()

print(f"Chinese American Museum visitors in July 2018: {ca_museum_jul18}")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Updated DataFrame setup with data from 2014 to 2018
data = {
    'Museum': [
        'Avila Adobe', 'Avila Adobe', 'Avila Adobe', 'Avila Adobe',
        'Firehouse Museum', 'Firehouse Museum', 'Firehouse Museum', 'Firehouse Museum',
        'Chinese American Museum', 'Chinese American Museum', 'Chinese American Museum', 'Chinese American Museum',
        'America Tropical Interpretive Center', 'America Tropical Interpretive Center', 'America Tropical Interpretive Center', 'America Tropical Interpretive Center'
    ],
    'Date': [
        '2014-07-01', '2015-07-01', '2016-07-01', '2017-07-01',
        '2014-07-01', '2015-07-01', '2016-07-01', '2017-07-01',
        '2014-07-01', '2015-07-01', '2016-07-01', '2017-07-01',
        '2014-07-01', '2015-07-01', '2016-07-01', '2017-07-01'
    ],
    'Visitors': [1000, 1100, 1200, 1300, 1500, 1600, 1700, 1800, 2620, 2700, 2800, 2900, 1300, 1400, 1500, 1600]
}

# Create DataFrame
df_museum_data = pd.DataFrame(data)

# Convert 'Date' to datetime format
df_museum_data['Date'] = pd.to_datetime(df_museum_data['Date'])

# Plotting
plt.figure(figsize=(14, 6))

# Line plot with hue for different museums
sns.lineplot(data=df_museum_data, x='Date', y='Visitors', hue='Museum')

# Adding titles and labels
plt.title('Monthly Visitors to Los Angeles City Museums (2014-2018)')
plt.xlabel('Date')
plt.ylabel('Number of Visitors')
plt.legend(title='Museum')

# Adjust x-axis to cover the full range from 2014 to 2018
plt.xlim(pd.Timestamp('2014-01-01'), pd.Timestamp('2018-12-31'))

# Show the plot
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Example DataFrame setup with data from 2014 to 2018
data = {
    'Museum': [
        'Avila Adobe', 'Avila Adobe', 'Avila Adobe', 'Avila Adobe',
        'Firehouse Museum', 'Firehouse Museum', 'Firehouse Museum', 'Firehouse Museum',
        'Chinese American Museum', 'Chinese American Museum', 'Chinese American Museum', 'Chinese American Museum',
        'America Tropical Interpretive Center', 'America Tropical Interpretive Center', 'America Tropical Interpretive Center', 'America Tropical Interpretive Center'
    ],
    'Date': [
        '2014-07-01', '2015-07-01', '2016-07-01', '2017-07-01',
        '2014-07-01', '2015-07-01', '2016-07-01', '2017-07-01',
        '2014-07-01', '2015-07-01', '2016-07-01', '2017-07-01',
        '2014-07-01', '2015-07-01', '2016-07-01', '2017-07-01'
    ],
    'Visitors': [1000, 1100, 1200, 1300, 1500, 1600, 1700, 1800, 2620, 2700, 2800, 2900, 1300, 1400, 1500, 1600]
}

# Create DataFrame
df_museum_data = pd.DataFrame(data)

# Convert 'Date' to datetime format
df_museum_data['Date'] = pd.to_datetime(df_museum_data['Date'])

# Filter data for Avila Adobe
avila_adobe_data = df_museum_data[df_museum_data['Museum'] == 'Avila Adobe']

# Plotting
plt.figure(figsize=(14, 6))

# Line plot for Avila Adobe
sns.lineplot(data=avila_adobe_data, x='Date', y='Visitors', label='Avila Adobe')

# Adding titles and labels
plt.title('Line Chart of Visitors to Avila Adobe Over Time')
plt.xlabel('Date')
plt.ylabel('Number of Visitors')
plt.legend(title='Museum')

# Adjust x-axis to cover the range from 2014 to 2018
plt.xlim(pd.Timestamp('2014-01-01'), pd.Timestamp('2018-12-31'))

# Show the plot
plt.show()